/**
 * GENERATED by scripts/td_ui.py - do not edit.
 *
 * Every interface piece: where it is, how to slice it, and how
 * thick its border has to be for the corners to be drawn at the
 * size they were cut. The component spreads this onto the
 * overlay, so the stylesheet can name a piece without knowing
 * its size or its path.
 */

/**
 * Where the pieces are, made absolute against the page rather than left
 * relative.
 *
 * A relative url() inside a custom property is resolved against the
 * STYLESHEET that reads it, not the element that carries it. In dev Vite
 * serves its CSS from a <style> tag, whose base is the document, so a
 * relative path is right and everything looked fine. In a build the CSS is a
 * real file under assets/, so the same path asked for assets/games/... and
 * every piece of the interface 404'd on the published site.
 */
const B = new URL("games/td/ui", document.baseURI).href;

export const UI_VARS: Record<string, string> = {
  "--tdui-paper": `url(${B}/paper.png)`,
  "--tdui-paper-slice": "20 24 21 24",
  "--tdui-paper-border": "20px 24px 21px 24px",
  "--tdui-slate": `url(${B}/slate.png)`,
  "--tdui-slate-slice": "20 25 20 25",
  "--tdui-slate-border": "20px 25px 20px 25px",
  "--tdui-chip": `url(${B}/chip.png)`,
  "--tdui-chip-slice": "11 13 10 13",
  "--tdui-chip-border": "11px 13px 10px 13px",
  "--tdui-chip-lit": `url(${B}/chip-lit.png)`,
  "--tdui-chip-lit-slice": "11 12 11 12",
  "--tdui-chip-lit-border": "11px 12px 11px 12px",
  "--tdui-wood": `url(${B}/wood.png)`,
  "--tdui-wood-slice": "34 34 41 34",
  "--tdui-wood-border": "34px 34px 41px 34px",
  "--tdui-banner": `url(${B}/banner.png)`,
  "--tdui-banner-slice": "29 35 47 42",
  "--tdui-banner-border": "29px 35px 47px 42px",
  "--tdui-button": `url(${B}/button.png)`,
  "--tdui-button-slice": "14 13 14 13",
  "--tdui-button-down": `url(${B}/button-down.png)`,
  "--tdui-button-down-slice": "12 15 12 15",
  "--tdui-big": `url(${B}/big.png)`,
  "--tdui-big-slice": "16 15 16 15",
  "--tdui-big-border": "16px 15px 16px 15px",
  "--tdui-big-down": `url(${B}/big-down.png)`,
  "--tdui-big-down-slice": "12 17 17 17",
  "--tdui-big-down-border": "12px 17px 17px 17px",
  "--tdui-round": `url(${B}/round.png)`,
  "--tdui-round-down": `url(${B}/round-down.png)`,
  "--tdui-bar": `url(${B}/bar.png)`,
  "--tdui-bar-slice": "1 10 1 10",
  "--tdui-bar-fill": `url(${B}/bar-fill.png)`,
  "--tdui-icon-gold": `url(${B}/icon-gold.png)`,
  "--tdui-icon-lives": `url(${B}/icon-lives.png)`,
  "--tdui-icon-wave": `url(${B}/icon-wave.png)`,
  "--tdui-icon-up": `url(${B}/icon-up.png)`,
  "--tdui-icon-sell": `url(${B}/icon-sell.png)`,
  "--tdui-icon-gear": `url(${B}/icon-gear.png)`,
  "--tdui-icon-info": `url(${B}/icon-info.png)`,
  "--tdui-icon-meat": `url(${B}/icon-meat.png)`,
};
