# -*- coding: utf-8 -*-
"""
Turn the painted maps into level backgrounds and the data that goes with them.

Each map was painted with its road and its build pads already on it, so the
game must follow the picture rather than the other way round. art-src/td/
maps.json holds what was traced off each one — the road as a polyline in board
space, and the centre of every pad — and this script publishes the artwork and
bakes that data into a TypeScript module the engine imports.

Two things it deliberately does NOT do: invent slots (the map already says
where they are) and resize at runtime (the background is published at the size
it is drawn).

Usage:
    python scripts/td_maps.py [--images]

The full-size paintings live in art-src/td/maps. Pass --images to republish
them; without it the script only re-emits maps.ts from maps.json.
"""
import json
import math
import os
import sys
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(ROOT, "art-src", "td")
OUT_IMG = os.path.join(ROOT, "public", "games", "td", "maps")
OUT_TS = os.path.join(ROOT, "src", "components", "td", "maps.ts")

#: the board is 960x540; the background ships at 4:3 of that, which is as
#: sharp as it ever gets drawn on a large screen
PUBLISH = (1280, 720)
QUALITY = 80
#: the board every traced point is measured in
W, H = 960, 540

HEADER = """/**
 * The five painted maps, and what was traced off each.
 *
 * GENERATED by scripts/td_maps.py from art-src/td/maps.json — do not edit.
 *
 * The road is the path the artist painted, sampled into board space, and the
 * plots are the pads they drew beside it. Both are data rather than geometry
 * the game invents, because the picture is the authority: a tower has to
 * stand on the pad that is visibly there, and creeps have to walk on the road
 * that is visibly there.
 */

import type { Point } from "./path";

export interface MapDef {
  id: string;
  /** background under public/games/td/maps */
  image: string;
  road: Point[];
  /** build pads, in the order they were traced */
  plots: Point[];
  /** gate facades drawn OVER the creeps, so they come out from behind the arch */
  overlay?: string;
  /**
   * Things a creep walks BEHIND, cut out of the map into a layer of their own.
   *
   * The map is one flat picture, so without this everything on it is behind
   * everything the game draws. Each piece carries the line it stands on, and
   * the game draws it after whoever is further up the board and before
   * whoever is further down.
   */
  props?: string;
  pieces?: { x: number; y: number; w: number; h: number; base: number }[];
  /**
   * The map's other ways across, each complete from its own gate to its own.
   *
   * Several maps are painted with more than one way through. Sending part of
   * every wave down the others is what stops half a map being scenery: the
   * plots along them are worth buying, and the player has more than one line
   * to hold. Each is stored whole — a way that shares the road for a while
   * carries that stretch of it — so nothing has to be decided at a junction.
   */
  branches?: Point[][];
}

export const MAPS: Record<string, MapDef> = {
"""


#: how far past the edge the road runs, so creeps walk on and off rather than
#: appearing and vanishing at the border
OVERRUN = 80
#: how close to the border an end has to be to count as reaching it
BORDER = 64
#: how much of the road's tail its heading off the board is taken from
AIM = 36
#: half the width of the road, in board px: the strip creeps actually walk on.
#: A gate may override it — a paved ramp is wider than a doorway.
BAND = 14


def extend_ends(road):
    """
    Run the first and last segment out past the edge of the board.

    The traced road starts and ends where the artist's stroke does, which is
    at the gate — so a creep would appear at the gate rather than walk in
    through it, and vanish at the far one instead of leaving.

    Only an end that reaches the border gets this. Not every way across ends
    at one: the glacier's second one ends at the mouth of an ice cave in the
    middle of the map, and running that on would march its creeps another
    eighty units into the mountain.
    """
    out = [list(p) for p in road]
    for a, step in ((0, 1), (len(out) - 1, -1)):
        x, y = out[a]
        if min(x, W - 1 - x, y, H - 1 - y) > BORDER:
            continue
        # aim along the last stretch rather than the last point: the sampling
        # is fine enough that one neighbour is mostly rounding, and the mine
        # trestle's exit leaves at 40 degrees, not flat
        b, i = a + step, a + step
        while 0 <= i < len(out) and math.dist(out[a], out[i]) < AIM:
            b, i = i, i + step
        dx, dy = out[a][0] - out[b][0], out[a][1] - out[b][1]
        n = (dx * dx + dy * dy) ** 0.5 or 1.0
        out[a] = [out[a][0] + dx / n * OVERRUN, out[a][1] + dy / n * OVERRUN]
    return out


def _dilate(m, r):
    out = m.copy()
    for dy in range(-r, r + 1):
        for dx in range(-r, r + 1):
            if dy or dx:
                out |= np.roll(np.roll(m, dy, axis=0), dx, axis=1)
    return out


def road_band(shape, road, half):
    """Pixels within `half` of the road's centreline."""
    h, w = shape
    yy, xx = np.mgrid[0:h, 0:w]
    near = np.zeros((h, w), dtype=bool)
    for i in range(len(road) - 1):
        (ax, ay), (bx, by) = road[i], road[i + 1]
        dx, dy = bx - ax, by - ay
        L2 = dx * dx + dy * dy or 1.0
        t = np.clip(((xx - ax) * dx + (yy - ay) * dy) / L2, 0, 1)
        near |= (xx - (ax + t * dx)) ** 2 + (yy - (ay + t * dy)) ** 2 <= half * half
    return near


def gate_overlay(board, road, gates):
    """
    The parts of the map that must be drawn OVER the creeps.

    A creep walking out of a gate has to come out from behind the arch, not
    across its face. Colour is no way to pick the arch out — its stones are
    the colour of the sand — so this goes by geometry: inside each gate's
    `box` everything is kept except the strip of road the creeps walk on;
    an `opening` is always left clear (the dark doorway they are seen
    through) and each of the `keeps` is always solid (a pillar the road runs
    right past, which the strip would otherwise cut the foot off). Feet stay
    visible on the road, bodies pass behind the stones, and the layer is
    drawn after the creeps.
    """
    a = np.asarray(board.convert("RGB"), dtype=np.uint8)
    h, w = a.shape[:2]
    band = road_band((h, w), road, BAND)
    out = np.zeros((h, w, 4), dtype=np.uint8)
    for g in gates:
        x0, y0, x1, y1 = g["box"]
        keep = np.zeros((h, w), dtype=bool)
        keep[y0:y1, x0:x1] = True
        keep &= ~(band if g.get("band", BAND) == BAND
                  else road_band((h, w), road, g["band"]))
        if "opening" in g:
            ox0, oy0, ox1, oy1 = g["opening"]
            keep[oy0:oy1, ox0:ox1] = False
        for (kx0, ky0, kx1, ky1) in g.get("keeps", []):
            keep[ky0:ky1, kx0:kx1] = True
        out[keep, :3] = a[keep]
        out[keep, 3] = 255
    return Image.fromarray(out, "RGBA")


def points(pairs):
    return ", ".join(f"{{ x: {round(x)}, y: {round(y)} }}" for x, y in pairs)


def wrap(label, pairs, indent=4):
    """One point per line would be 400 lines; four per line reads fine."""
    pad = " " * (indent + 2)
    out = [f"{' ' * indent}{label}: ["]
    for i in range(0, len(pairs), 4):
        out.append(pad + points(pairs[i:i + 4]) + ",")
    out.append(f"{' ' * indent}],")
    return "\n".join(out)


def main():
    data = json.load(open(os.path.join(ART, "maps.json"), encoding="utf-8"))
    src = os.path.join(ART, "maps") if "--images" in sys.argv[1:] else None

    if src:
        os.makedirs(OUT_IMG, exist_ok=True)
        for mid, m in data.items():
            p = os.path.join(src, m["source"])
            if not os.path.exists(p):
                print(f"  !! missing source for {mid}: {m['source']}")
                continue
            im = Image.open(p).convert("RGB").resize(PUBLISH, Image.LANCZOS)
            dst = os.path.join(OUT_IMG, f"{mid}.webp")
            im.save(dst, "WEBP", quality=QUALITY, method=6)
            print(f"  {mid}: {os.path.getsize(dst) / 1024:.0f} kB")
            if m.get("gates"):
                # keyed on the 960x540 board, published at the map's size
                board = im.resize((960, 540), Image.LANCZOS)
                over = gate_overlay(board, m["road"], m["gates"])
                over = over.resize(PUBLISH, Image.LANCZOS)
                dst = os.path.join(OUT_IMG, f"{mid}.over.webp")
                over.save(dst, "WEBP", quality=92, method=6)
                print(f"  {mid} gates: {os.path.getsize(dst) / 1024:.0f} kB")

    body = [HEADER]
    for mid, m in data.items():
        body.append(f'  {mid}: {{\n    id: "{mid}",\n    image: "{mid}.webp",')
        if m.get("gates"):
            body.append(f'    overlay: "{mid}.over.webp",')
        if m.get("pieces"):
            body.append(f'    props: "{mid}.props.webp",')
            body.append("    pieces: [")
            for p in m["pieces"]:
                body.append(f'      {{ x: {p["x"]}, y: {p["y"]}, w: {p["w"]}, '
                            f'h: {p["h"]}, base: {p["base"]} }},')
            body.append("    ],")
        body.append(wrap("road", extend_ends(m["road"])))
        if m.get("branches"):
            body.append("    branches: [")
            for lane in m["branches"]:
                body.append(wrap("", extend_ends(lane), indent=6).replace(": [", "[", 1))
            body.append("    ],")
        body.append(wrap("plots", m["plots"]))
        body.append("  },")
    body.append("};\n")
    with open(OUT_TS, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(body))
    print(f"wrote {os.path.relpath(OUT_TS, ROOT)} with {len(data)} maps")


if __name__ == "__main__":
    main()
