# -*- coding: utf-8 -*-
"""
Turn the painted maps into level backgrounds and the data that goes with them.

Each map was painted with its road and its build pads already on it, so the
game must follow the picture rather than the other way round. art-src/td/
maps.json holds what was traced off each one — the road as a polyline in board
space, and the centre of every pad — and this script publishes the artwork and
bakes that data into a TypeScript module the engine imports.

Two things it deliberately does NOT do: invent slots (the map already says
where they are) and resize at runtime (the background is published at the size
it is drawn).

Usage:
    python scripts/td_maps.py [--images]

The full-size paintings live in art-src/td/maps. Pass --images to republish
them; without it the script only re-emits maps.ts from maps.json.
"""
import json
import os
import sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(ROOT, "art-src", "td")
OUT_IMG = os.path.join(ROOT, "public", "games", "td", "maps")
OUT_TS = os.path.join(ROOT, "src", "components", "td", "maps.ts")

#: the board is 960x540; the background ships at 4:3 of that, which is as
#: sharp as it ever gets drawn on a large screen
PUBLISH = (1280, 720)
QUALITY = 80

HEADER = """/**
 * The five painted maps, and what was traced off each.
 *
 * GENERATED by scripts/td_maps.py from art-src/td/maps.json — do not edit.
 *
 * The road is the path the artist painted, sampled into board space, and the
 * plots are the pads they drew beside it. Both are data rather than geometry
 * the game invents, because the picture is the authority: a tower has to
 * stand on the pad that is visibly there, and creeps have to walk on the road
 * that is visibly there.
 */

import type { Point } from "./path";

export interface MapDef {
  id: string;
  /** background under public/games/td/maps */
  image: string;
  road: Point[];
  /** build pads, in the order they were traced */
  plots: Point[];
}

export const MAPS: Record<string, MapDef> = {
"""


#: how far past the edge the road runs, so creeps walk on and off rather than
#: appearing and vanishing at the border
OVERRUN = 80


def extend_ends(road):
    """Run the first and last segment out past the edge of the board."""
    out = [list(p) for p in road]
    for a, b in ((0, 1), (-1, -2)):
        dx, dy = out[a][0] - out[b][0], out[a][1] - out[b][1]
        n = (dx * dx + dy * dy) ** 0.5 or 1.0
        out[a] = [out[a][0] + dx / n * OVERRUN, out[a][1] + dy / n * OVERRUN]
    return out


def points(pairs):
    return ", ".join(f"{{ x: {round(x)}, y: {round(y)} }}" for x, y in pairs)


def wrap(label, pairs, indent=4):
    """One point per line would be 400 lines; four per line reads fine."""
    pad = " " * (indent + 2)
    out = [f"{' ' * indent}{label}: ["]
    for i in range(0, len(pairs), 4):
        out.append(pad + points(pairs[i:i + 4]) + ",")
    out.append(f"{' ' * indent}],")
    return "\n".join(out)


def main():
    data = json.load(open(os.path.join(ART, "maps.json"), encoding="utf-8"))
    src = os.path.join(ART, "maps") if "--images" in sys.argv[1:] else None

    if src:
        os.makedirs(OUT_IMG, exist_ok=True)
        for mid, m in data.items():
            p = os.path.join(src, m["source"])
            if not os.path.exists(p):
                print(f"  !! missing source for {mid}: {m['source']}")
                continue
            im = Image.open(p).convert("RGB").resize(PUBLISH, Image.LANCZOS)
            dst = os.path.join(OUT_IMG, f"{mid}.webp")
            im.save(dst, "WEBP", quality=QUALITY, method=6)
            print(f"  {mid}: {os.path.getsize(dst) / 1024:.0f} kB")

    body = [HEADER]
    for mid, m in data.items():
        body.append(f'  {mid}: {{\n    id: "{mid}",\n    image: "{mid}.webp",')
        body.append(wrap("road", extend_ends(m["road"])))
        body.append(wrap("plots", m["plots"]))
        body.append("  },")
    body.append("};\n")
    with open(OUT_TS, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(body))
    print(f"wrote {os.path.relpath(OUT_TS, ROOT)} with {len(data)} maps")


if __name__ == "__main__":
    main()
